# Window size
WIDTH, HEIGHT = 700, 500

# Ball Variables
BALL_RADIUS = 15
BALL_COLOR = (255,255,255)
BALL_VEL = 2

# PADDLE VARIABLES
PADDLE_WIDTH, PADDLE_HEIGHT = 20, 100

# PADDING
LEFT_OFFSET = PADDLE_WIDTH
RIGHT_OFFSET = WIDTH - LEFT_OFFSET

# speed increment factor
SPEED_INCREMENT = 1.25

# Score to min
MAX_SCORE = 5